// Copyright (c) Alpaca Core
// SPDX-License-Identifier: MIT
//
#pragma once

#define AC_FRAME_VERSION_MAJOR @PROJECT_VERSION_MAJOR@
#define AC_FRAME_VERSION_MINOR @PROJECT_VERSION_MINOR@
#define AC_FRAME_VERSION_PATCH @PROJECT_VERSION_PATCH@

#define AC_FRAME_VERSION_STRING "@PROJECT_VERSION@"
