// Copyright (c) Borislav Stanimirov
// SPDX-License-Identifier: MIT
//
#pragma once

#define AC_VERSION_MAJOR @PROJECT_VERSION_MAJOR@
#define AC_VERSION_MINOR @PROJECT_VERSION_MINOR@
#define AC_VERSION_PATCH @PROJECT_VERSION_PATCH@
#define AC_VERSION_TAG "@PROJECT_VERSION_TAG@"

#define AC_VERSION_STRING "@PROJECT_VERSION@@PROJECT_VERSION_TAG@"
