// Copyright (c) Alpaca Core
// SPDX-License-Identifier: MIT
//
#include "ac-repo-root.h"

// this file can be generated by cmake
// shall we do it?

#define TEST_ASSETS_PATH AC_REPO_ROOT "/common/ac-test-assets/test-assets"

#define TEST_ASSETS_BINARY_PATH TEST_ASSETS_PATH "/binary"

#define TA_BINARY_FILE "test-binary-file.bin"
#define TA_BINARY_FILE_SIZE 92

#define TA_ANOTHER_BINARY_FILE "another-test-file.bin"
#define TA_ANOTHER_BINARY_FILE_SIZE 29
