// Copyright (c) Alpaca Core
// SPDX-License-Identifier: MIT
//

// this file can be entirely generated by cmake
// shall we do it?

#define TEST_ASSETS_PATH "@CMAKE_CURRENT_SOURCE_DIR@/test-assets"

#define TEST_ASSETS_BINARY_PATH TEST_ASSETS_PATH "/binary"

#define TA_BINARY_FILE "test-binary-file.bin"
#define TA_BINARY_FILE_SIZE 92

#define TA_ANOTHER_BINARY_FILE "another-test-file.bin"
#define TA_ANOTHER_BINARY_FILE_SIZE 29
